import type { ExperienceDefinition } from "@/lib/portfolio-types";

export const experiences: readonly ExperienceDefinition[] = [
  {
    id: "airtel-digital",
    title: "Data Platform Engineer / Architect",
    company: "Airtel Digital",
    companyUrl: "https://careers.airtel.com",
    type: "employment",
    description:
      "I architect and build governed data platforms, metadata services, workflow orchestration, access-governance integrations, in-house CI/CD onboarding, and network-scale analytics systems.",
    date: "2021 - present",
    icon: "/project_img/org-airtel.png",
    focusWeights: {
      general: 1,
      ai: 0.8,
      "agentic-development": 0.8,
      "backend-engineering": 0.5,
      "platform-engineering": 0.9,
      "data-platform": 1,
      flink: 0.7,
      kafka: 0.7,
    },
    bullets: [
      {
        id: "airtel-conversational-data",
        text: "Architected and built a governed conversational data platform for text-to-data workflows: multi-LLM subgraphs, knowledge retrieval, controlled query execution, answer reasoning, chart generation, prompt tracing, and platform orchestration.",
        skillIds: [
          "python",
          "fastapi",
          "langgraph",
          "langfuse",
          "trino",
          "datahub",
          "llm-workflows",
        ],
        focusWeights: {
          general: 1,
          ai: 1,
          "agentic-development": 1,
          "backend-engineering": 0.8,
          "platform-engineering": 0.9,
          "data-platform": 0.9,
          python: 0.9,
        },
        visibility: "public",
      },
      {
        id: "airtel-metadata-governance",
        text: "Designed and implemented Hive metadata synchronization for independent Hive environments, combining real-time listener sync, daily reconciliation, missed-addition/removal repair, sync-duration expiry cleanup, one-time interval jobs, observability, and deployment hardening.",
        skillIds: ["java", "hive", "spark", "airflow"],
        focusWeights: {
          general: 1,
          "platform-engineering": 0.9,
          "data-platform": 1,
        },
        visibility: "public",
      },
      {
        id: "airtel-ranger-governance",
        text: "Extended Apache Ranger-based access governance with an external attribute store, DataHub tag-driven policies, row-level security, masking, Trino integration, clearer audit/error paths, and local/containerized runtime support.",
        skillIds: ["ranger", "trino", "datahub", "java", "kubernetes"],
        focusWeights: {
          general: 0.8,
          "backend-engineering": 0.7,
          "platform-engineering": 1,
          "data-platform": 0.9,
        },
        visibility: "public",
      },
      {
        id: "airtel-self-service-data-platform",
        text: "Built governed self-service data platform capabilities around Kyuubi customizations, Trino query access, DataHub metadata, dbt transformations, Metabase BI, RBAC, and secrets management.",
        skillIds: ["kyuubi", "trino", "datahub", "dbt", "metabase", "ranger"],
        focusWeights: {
          general: 0.9,
          "platform-engineering": 1,
          "data-platform": 1,
        },
        visibility: "public",
      },
      {
        id: "airtel-cicd-dx",
        text: "Created an in-house YAML-driven CI/CD onboarding framework that reduced onboarding time by about 40%, with Jenkins runner and Docker-agent build modes, mandatory pre-commit checks, unit-test reporting, security scans, deployment templates, and Jira-triggered workflow/status integration.",
        skillIds: [
          "internal-cicd",
          "jenkins",
          "docker",
          "helm",
          "kubernetes",
          "jira",
        ],
        focusWeights: {
          general: 0.8,
          "platform-engineering": 1,
          "data-platform": 0.8,
          python: 0.6,
        },
        visibility: "public",
      },
      {
        id: "airtel-ocp-spark-migration",
        text: "Migrated 50+ Spark and data workloads to Red Hat OCP using Spark Operator, shared CI/CD, Docker/Helm packaging, and Kubernetes runtime conventions, reducing infrastructure cost by about 30%.",
        skillIds: [
          "kubernetes",
          "spark-operator",
          "spark",
          "internal-cicd",
          "docker",
          "helm",
        ],
        focusWeights: {
          general: 0.85,
          "platform-engineering": 1,
          "data-platform": 0.9,
        },
        visibility: "public",
      },
      {
        id: "airtel-ingestion-analytics",
        text: "Built mobile tower network-event analytics, browsing-log data products, and real-time point-of-interest proximity pipelines, including petabyte-scale aggregation, safe-browsing classification, audience cohorts, and location-triggered downstream actions.",
        skillIds: [
          "flink",
          "kafka",
          "spark",
          "airflow",
          "seatunnel",
          "kyuubi",
          "trino",
          "sql",
          "nifi",
          "geospatial",
        ],
        focusWeights: {
          general: 0.9,
          "backend-engineering": 0.6,
          "platform-engineering": 0.7,
          "data-platform": 1,
          python: 0.6,
        },
        visibility: "public",
      },
    ],
  },
  {
    id: "dunnhumby",
    title: "Data Science Engineer",
    company: "dunnhumby",
    companyUrl: "https://www.dunnhumby.com/careers/",
    type: "employment",
    description:
      "I worked between data science and big-data platform teams, turning statistical and ML analysis into reusable pipelines, data marts, reporting products, and client-ready analytics workflows.",
    date: "2018 - 2021",
    icon: "/project_img/org-dh.jpg",
    focusWeights: {
      general: 0.8,
      ai: 0.4,
      "data-platform": 0.8,
      python: 0.7,
    },
    bullets: [
      {
        id: "dh-bridge",
        text: "Worked as a bridge between data science and big data platform teams by turning analytical work into reusable products and repeatable pipelines.",
        skillIds: ["python", "spark", "sql"],
        focusWeights: {
          general: 0.7,
          ai: 0.5,
          "data-platform": 0.8,
          python: 0.8,
        },
        visibility: "public",
      },
      {
        id: "dh-retail",
        text: "Built customer segmentation, data marts, reporting platforms, and retail optimization analytics for large datasets, including category/adjacency work associated with up to 20% sales-growth impact.",
        skillIds: ["spark", "python", "sql", "airflow", "power-bi"],
        focusWeights: {
          general: 0.7,
          ai: 0.4,
          "data-platform": 0.8,
          python: 0.7,
        },
        visibility: "public",
      },
      {
        id: "dh-products",
        text: "Created reusable retail analytics workflows across customer priority assortment, cross-shopping behavior, direct-mail promotion planning, category uplift, and seasonality analysis.",
        skillIds: ["spark", "python", "airflow"],
        focusWeights: {
          general: 0.7,
          "data-platform": 0.8,
          python: 0.6,
        },
        visibility: "public",
      },
    ],
  },
  {
    id: "mphasis",
    title: "Software Engineer",
    company: "Mphasis",
    companyUrl: "https://careers.mphasis.com/home.html",
    type: "employment",
    description:
      "I worked on mainframe and big-data systems for insurance and telecom clients, including Spark migration work and automation that saved 500+ manual hours per year.",
    date: "2014 - 2018",
    icon: "/project_img/org-mphasis.png",
    focusWeights: {
      general: 0.7,
      "backend-engineering": 0.7,
      "platform-engineering": 0.5,
      "data-platform": 0.6,
    },
    bullets: [
      {
        id: "mphasis-migration",
        text: "Worked in both mainframe and big data ecosystems and contributed to migration from mainframe workloads to Spark-based processing.",
        skillIds: ["spark", "java", "sql"],
        focusWeights: {
          general: 0.6,
          "backend-engineering": 0.5,
          "data-platform": 0.7,
        },
        visibility: "public",
      },
      {
        id: "mphasis-automation",
        text: "Built automations that saved 500+ manual hours per year by removing repetitive workflow steps.",
        skillIds: ["python", "java"],
        focusWeights: {
          general: 0.6,
          "backend-engineering": 0.7,
          "platform-engineering": 0.4,
          python: 0.5,
        },
        visibility: "public",
      },
      {
        id: "mphasis-clients",
        text: "Worked as a developer for insurance and telecom clients across enterprise systems and data workflows.",
        skillIds: ["java", "sql", "spark"],
        focusWeights: {
          general: 0.5,
          "backend-engineering": 0.6,
          "data-platform": 0.5,
        },
        visibility: "public",
      },
    ],
  },
] as const;
