import type { SkillDefinition } from "@/lib/portfolio-types";

export const skillDefinitions: readonly SkillDefinition[] = [
  {
    id: "spark",
    label: "Spark",
    category: "framework",
    aliases: ["spark", "apache spark", "pyspark"],
    focusWeights: {
      general: 0.9,
      "data-platform": 1,
      python: 0.6,
    },
  },
  {
    id: "flink",
    label: "Flink",
    category: "framework",
    aliases: ["flink", "apache flink"],
    focusWeights: {
      general: 0.9,
      "backend-engineering": 0.35,
      "platform-engineering": 0.25,
      "data-platform": 0.85,
      flink: 1,
      kafka: 0.45,
    },
  },
  {
    id: "kubernetes",
    label: "Kubernetes (OCP)",
    category: "platform",
    aliases: ["kubernetes", "k8s", "openshift", "ocp"],
    focusWeights: {
      general: 0.6,
      "platform-engineering": 1,
      "backend-engineering": 0.3,
    },
  },
  {
    id: "spark-operator",
    label: "Spark Operator",
    category: "platform",
    aliases: [
      "spark operator",
      "kubernetes spark operator",
      "spark on kubernetes",
    ],
    focusWeights: {
      general: 0.45,
      "platform-engineering": 0.85,
      "data-platform": 0.75,
    },
  },
  {
    id: "python",
    label: "Python",
    category: "language",
    aliases: ["python", "python3"],
    focusWeights: {
      general: 0.9,
      ai: 0.9,
      "agentic-development": 0.8,
      "backend-engineering": 0.7,
      "data-platform": 0.8,
      python: 1,
    },
  },
  {
    id: "java",
    label: "Java",
    category: "language",
    aliases: ["java"],
    focusWeights: {
      general: 0.8,
      "backend-engineering": 0.8,
      "data-platform": 0.7,
      flink: 0.7,
      kafka: 0.6,
    },
  },
  {
    id: "scala",
    label: "Scala",
    category: "language",
    aliases: ["scala"],
    focusWeights: {
      general: 0.45,
      "backend-engineering": 0.5,
      "data-platform": 0.7,
      flink: 0.35,
      kafka: 0.35,
    },
  },
  {
    id: "javascript",
    label: "JavaScript",
    category: "language",
    aliases: ["javascript", "js", "typescript", "ts"],
    focusWeights: {
      general: 0.35,
      "backend-engineering": 0.55,
      ai: 0.25,
      "agentic-development": 0.25,
    },
  },
  {
    id: "typescript",
    label: "TypeScript",
    category: "language",
    aliases: ["typescript", "ts"],
    focusWeights: {
      general: 0.35,
      "backend-engineering": 0.55,
      ai: 0.25,
      "agentic-development": 0.25,
    },
  },
  {
    id: "mongodb",
    label: "MongoDB",
    category: "data",
    aliases: ["mongodb", "mongo"],
    focusWeights: {
      general: 0.3,
      "backend-engineering": 0.5,
    },
  },
  {
    id: "cloud",
    label: "Cloud (GCP, AWS, Azure)",
    category: "platform",
    aliases: [
      "gcp",
      "aws",
      "azure",
      "cloud",
      "google cloud",
      "amazon web services",
      "microsoft azure",
    ],
    focusWeights: {
      general: 0.5,
      "platform-engineering": 0.7,
      "data-platform": 0.5,
    },
  },
  {
    id: "kafka",
    label: "Kafka",
    category: "platform",
    aliases: ["kafka", "apache kafka"],
    focusWeights: {
      general: 0.6,
      "backend-engineering": 0.6,
      "platform-engineering": 0.55,
      "data-platform": 0.5,
      flink: 0.45,
      kafka: 1,
    },
  },
  {
    id: "elastic-stack",
    label: "Elastic Stack",
    category: "tooling",
    aliases: ["elastic stack", "elasticsearch", "kibana", "elastic"],
    focusWeights: {
      general: 0.5,
      "platform-engineering": 0.7,
      "data-platform": 0.4,
      kafka: 0.3,
    },
  },
  {
    id: "nifi",
    label: "NiFi",
    category: "tooling",
    aliases: ["nifi", "apache nifi"],
    focusWeights: {
      "data-platform": 0.7,
    },
  },
  {
    id: "datahub",
    label: "DataHub",
    category: "tooling",
    aliases: ["datahub"],
    focusWeights: {
      "platform-engineering": 0.5,
      "data-platform": 0.8,
    },
  },
  {
    id: "dbt",
    label: "dbt",
    category: "tooling",
    aliases: ["dbt"],
    focusWeights: {
      "data-platform": 0.7,
    },
  },
  {
    id: "airflow",
    label: "Airflow",
    category: "platform",
    aliases: ["airflow", "apache airflow"],
    focusWeights: {
      general: 0.5,
      "platform-engineering": 0.6,
      "data-platform": 0.8,
      python: 0.4,
    },
  },
  {
    id: "hive",
    label: "Apache Hive",
    category: "data",
    aliases: ["hive", "apache hive", "hive metastore", "metastore"],
    focusWeights: {
      "platform-engineering": 0.6,
      "data-platform": 0.8,
    },
  },
  {
    id: "iceberg",
    label: "Apache Iceberg",
    category: "data",
    aliases: ["iceberg", "apache iceberg", "table format"],
    focusWeights: {
      general: 0.35,
      "data-platform": 0.75,
      "platform-engineering": 0.35,
    },
  },
  {
    id: "hudi",
    label: "Apache Hudi",
    category: "data",
    aliases: ["hudi", "apache hudi", "data lake table format"],
    focusWeights: {
      general: 0.35,
      "data-platform": 0.75,
      "platform-engineering": 0.35,
    },
  },
  {
    id: "influx",
    label: "Influx",
    category: "data",
    aliases: ["influx", "influxdb"],
    focusWeights: {
      general: 0.3,
      "data-platform": 0.4,
      "platform-engineering": 0.4,
    },
  },
  {
    id: "grafana",
    label: "Grafana",
    category: "tooling",
    aliases: ["grafana"],
    focusWeights: {
      "platform-engineering": 0.7,
      "data-platform": 0.25,
    },
  },
  {
    id: "kyuubi",
    label: "Apache Kyuubi",
    category: "tooling",
    aliases: ["kyuubi", "apache kyuubi"],
    focusWeights: {
      general: 0.4,
      "data-platform": 0.8,
      "platform-engineering": 0.5,
    },
  },
  {
    id: "trino",
    label: "Trino",
    category: "tooling",
    aliases: ["trino"],
    focusWeights: {
      general: 0.5,
      "backend-engineering": 0.3,
      "data-platform": 0.8,
    },
  },
  {
    id: "alluxio",
    label: "Alluxio",
    category: "platform",
    aliases: ["alluxio"],
    focusWeights: {
      "data-platform": 0.7,
    },
  },
  {
    id: "jupyter",
    label: "Jupyter",
    category: "tooling",
    aliases: ["jupyter", "jupyter notebook"],
    focusWeights: {
      general: 0.2,
      "data-platform": 0.6,
    },
  },
  {
    id: "power-bi",
    label: "Power BI",
    category: "tooling",
    aliases: ["power bi", "powerbi"],
    focusWeights: {
      general: 0.5,
      "data-platform": 0.6,
      python: 0.3,
    },
  },
  {
    id: "sql",
    label: "SQL",
    category: "data",
    aliases: ["sql", "postgresql", "postgres"],
    focusWeights: {
      general: 0.8,
      "backend-engineering": 0.6,
      "data-platform": 0.9,
      python: 0.4,
    },
  },
  {
    id: "postgres",
    label: "Postgres",
    category: "data",
    aliases: ["postgres", "postgresql"],
    focusWeights: {
      ai: 0.4,
      "agentic-development": 0.5,
      "backend-engineering": 0.9,
      "platform-engineering": 0.4,
      "data-platform": 0.4,
      python: 0.3,
    },
  },
  {
    id: "react",
    label: "React",
    category: "framework",
    aliases: ["react"],
    focusWeights: {
      general: 0.2,
      "backend-engineering": 0.2,
    },
  },
  {
    id: "nextjs",
    label: "Next.js",
    category: "framework",
    aliases: ["next.js", "nextjs", "next js"],
    focusWeights: {
      "agentic-development": 0.4,
      "backend-engineering": 0.3,
    },
  },
  {
    id: "tailwind",
    label: "Tailwind",
    category: "framework",
    aliases: ["tailwind", "tailwind css"],
    focusWeights: {
      general: 0.1,
    },
  },
  {
    id: "prisma",
    label: "Prisma",
    category: "tooling",
    aliases: ["prisma"],
    focusWeights: {
      "backend-engineering": 0.4,
    },
  },
  {
    id: "fastapi",
    label: "FastAPI",
    category: "framework",
    aliases: ["fastapi"],
    focusWeights: {
      ai: 0.4,
      "agentic-development": 0.7,
      "backend-engineering": 1,
      python: 0.8,
    },
  },
  {
    id: "nodejs",
    label: "Node.js",
    category: "platform",
    aliases: ["node.js", "nodejs", "node"],
    focusWeights: {
      general: 0.3,
      "backend-engineering": 0.5,
    },
  },
  {
    id: "apriori",
    label: "Apriori",
    category: "tooling",
    aliases: ["apriori", "association rules"],
    focusWeights: {
      general: 0.2,
      "data-platform": 0.3,
      python: 0.2,
    },
  },
  {
    id: "astro",
    label: "Astro",
    category: "framework",
    aliases: ["astro"],
    focusWeights: {
      general: 0.1,
      "backend-engineering": 0.1,
    },
  },
  {
    id: "vector-search",
    label: "Vector Search",
    category: "ai",
    aliases: ["vector search", "vector database", "embedding search", "rag"],
    focusWeights: {
      ai: 0.8,
      "agentic-development": 0.8,
      python: 0.3,
    },
  },
  {
    id: "context-engineering",
    label: "Context Engineering",
    category: "ai",
    aliases: [
      "context engineering",
      "context window design",
      "schema grounding",
      "retrieval grounding",
    ],
    focusWeights: {
      ai: 1,
      "agentic-development": 0.9,
      python: 0.3,
    },
  },
  {
    id: "genai",
    label: "Generative AI",
    category: "ai",
    aliases: ["genai", "generative ai", "generative-ai", "llm systems"],
    focusWeights: {
      ai: 1,
      "agentic-development": 0.7,
    },
  },
  {
    id: "llm-workflows",
    label: "LLM Orchestration",
    category: "ai",
    aliases: [
      "llm",
      "agent",
      "agentic",
      "llm orchestration",
      "llm workflows",
      "evaluation",
    ],
    focusWeights: {
      ai: 1,
      "agentic-development": 1,
    },
  },
  {
    id: "agent-orchestration",
    label: "Agent Orchestration",
    category: "ai",
    aliases: [
      "agent orchestration",
      "agent harness",
      "agent runtime",
      "agent workflow",
    ],
    focusWeights: {
      ai: 1,
      "agentic-development": 1,
      python: 0.3,
    },
  },
  {
    id: "langgraph",
    label: "LangGraph",
    category: "framework",
    aliases: ["langgraph", "graph orchestration", "agent graph", "subgraph"],
    focusWeights: {
      ai: 1,
      "agentic-development": 1,
      python: 0.4,
    },
  },
  {
    id: "rag",
    label: "RAG",
    category: "ai",
    aliases: [
      "rag",
      "retrieval augmented generation",
      "retrieval-augmented generation",
      "retrieval grounded",
    ],
    focusWeights: {
      ai: 1,
      "agentic-development": 0.9,
      python: 0.3,
    },
  },
  {
    id: "mcp",
    label: "MCP (Model Context Protocol)",
    category: "ai",
    aliases: [
      "mcp",
      "model context protocol",
      "mcp server",
      "mcp servers",
      "tool servers",
    ],
    focusWeights: {
      ai: 0.8,
      "agentic-development": 1,
    },
  },
  {
    id: "prompt-engineering",
    label: "Prompt Engineering",
    category: "ai",
    aliases: [
      "prompt engineering",
      "prompt design",
      "prompt management",
      "prompt tuning",
    ],
    focusWeights: {
      ai: 0.9,
      "agentic-development": 0.8,
    },
  },
  {
    id: "langfuse",
    label: "Langfuse",
    category: "tooling",
    aliases: ["langfuse", "prompt tracing", "prompt management", "llm tracing"],
    focusWeights: {
      ai: 0.8,
      "agentic-development": 0.8,
    },
  },
  {
    id: "openwebui",
    label: "Open WebUI",
    category: "platform",
    aliases: ["openwebui", "open webui", "chat ui", "rich ui"],
    focusWeights: {
      ai: 0.5,
      "agentic-development": 0.7,
    },
  },
  {
    id: "opa",
    label: "OPA (Open Policy Agent)",
    category: "platform",
    aliases: ["opa", "open policy agent", "rego", "policy engine", "opal", "cedar", "keycloak", "ldap", "data masking", "row-level security", "rls", "access governance"],
    focusWeights: {
      "backend-engineering": 0.6,
      "platform-engineering": 1,
      "data-platform": 0.7,
    },
  },
  {
    id: "ranger",
    label: "Apache Ranger",
    category: "platform",
    aliases: ["ranger", "apache ranger", "rbac", "data access governance"],
    focusWeights: {
      "platform-engineering": 0.8,
      "data-platform": 0.8,
      "backend-engineering": 0.4,
    },
  },
  {
    id: "seatunnel",
    label: "Apache SeaTunnel",
    category: "data",
    aliases: ["seatunnel", "apache seatunnel", "data ingestion"],
    focusWeights: {
      "data-platform": 0.7,
      "platform-engineering": 0.5,
    },
  },
  {
    id: "helm",
    label: "Helm",
    category: "tooling",
    aliases: ["helm", "helm charts", "kubernetes deployment"],
    focusWeights: {
      "platform-engineering": 0.7,
      "data-platform": 0.4,
    },
  },
  {
    id: "internal-cicd",
    label: "In-house CI/CD YAML",
    category: "tooling",
    aliases: [
      "internal cicd",
      "workflow file",
      "ci/cd",
      "cicd",
      "pipeline yaml",
    ],
    focusWeights: {
      "platform-engineering": 0.7,
      "backend-engineering": 0.3,
    },
  },
  {
    id: "jenkins",
    label: "Jenkins",
    category: "tooling",
    aliases: ["jenkins", "jenkins runner", "jenkins pipeline"],
    focusWeights: {
      "platform-engineering": 0.65,
      "backend-engineering": 0.25,
    },
  },
  {
    id: "docker",
    label: "Docker",
    category: "platform",
    aliases: ["docker", "docker agent", "container build"],
    focusWeights: {
      "platform-engineering": 0.55,
      "backend-engineering": 0.35,
    },
  },
  {
    id: "linux",
    label: "Linux",
    category: "platform",
    aliases: ["linux", "shell", "scripting", "unix"],
    focusWeights: {
      general: 0.45,
      "platform-engineering": 0.65,
      "backend-engineering": 0.45,
      "data-platform": 0.45,
    },
  },
  {
    id: "jira",
    label: "Jira",
    category: "tooling",
    aliases: ["jira", "ticket workflow", "issue transition"],
    focusWeights: {
      "platform-engineering": 0.45,
      "backend-engineering": 0.2,
    },
  },
  {
    id: "metabase",
    label: "Metabase",
    category: "tooling",
    aliases: ["metabase", "bi", "business intelligence", "dashboard"],
    focusWeights: {
      "data-platform": 0.5,
      "platform-engineering": 0.25,
    },
  },
  {
    id: "geospatial",
    label: "Geospatial streaming",
    category: "data",
    aliases: [
      "geospatial",
      "gps",
      "triangulation",
      "point of interest",
      "poi",
      "geofence",
    ],
    focusWeights: {
      "data-platform": 0.7,
      "platform-engineering": 0.45,
      flink: 0.8,
      kafka: 0.6,
    },
  },
  {
    id: "multi-agent-systems",
    label: "Multi-Agent Systems",
    category: "ai",
    aliases: [
      "multi-agent",
      "multi agent",
      "agent orchestration",
      "agent systems",
      "supervisor pattern",
    ],
    highlights: [
      "Production multi-agent orchestration with supervisor and worker patterns",
    ],
    focusWeights: {
      general: 0.8,
      ai: 1,
      "agentic-development": 1,
      "platform-engineering": 0.5,
    },
  },
  {
    id: "agent-harness",
    label: "Agent Harness",
    category: "ai",
    aliases: [
      "agent harness",
      "agent runtime",
      "agent framework",
      "agent infrastructure",
    ],
    highlights: [
      "Custom agent runtime with tool routing, state management, and recovery",
    ],
    focusWeights: {
      general: 0.7,
      ai: 1,
      "agentic-development": 1,
      "backend-engineering": 0.6,
    },
  },
  {
    id: "evals",
    label: "AI Evals",
    category: "ai",
    aliases: [
      "evals",
      "evaluation",
      "ai evaluation",
      "model evaluation",
      "eval framework",
      "RAGAS",
    ],
    highlights: [
      "Evaluation framework design for production LLM systems",
    ],
    focusWeights: { general: 0.7, ai: 1, "agentic-development": 0.8 },
  },
  {
    id: "ai-observability",
    label: "AI Observability",
    category: "ai",
    aliases: [
      "ai observability",
      "llm observability",
      "prompt tracing",
      "inference monitoring",
    ],
    highlights: [
      "Production observability with Langfuse for LLM pipelines",
    ],
    focusWeights: {
      general: 0.6,
      ai: 1,
      "platform-engineering": 0.7,
    },
  },
  {
    id: "tool-use",
    label: "Tool Use & Function Calling",
    category: "ai",
    aliases: [
      "tool use",
      "function calling",
      "tool calling",
      "structured outputs",
    ],
    highlights: [
      "MCP-based tool integration and function calling for agent systems",
    ],
    focusWeights: {
      general: 0.6,
      ai: 1,
      "agentic-development": 1,
    },
  },
  {
    id: "production-ai",
    label: "Production AI",
    category: "ai",
    aliases: [
      "production ai",
      "production llm",
      "ai infrastructure",
      "ai systems",
      "applied ai",
    ],
    highlights: [
      "Shipping AI systems with guardrails, observability, and cost controls",
    ],
    focusWeights: {
      general: 0.8,
      ai: 1,
      "platform-engineering": 0.8,
      "backend-engineering": 0.6,
    },
  },
] as const;
